lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem' # Ruta de la clau privada
    public_key: '%kernel.project_dir%/config/jwt/public.pem'  # Ruta de la clau pública
    pass_phrase: '%env(JWT_PASSPHRASE)%'                     # Contrasenya de la clau privada
    token_ttl: 3600                                         # Durada del token en segons (1 hora)